name: Amalgam Script

permissions:
  contents: write
  actions: read

on:
  - push

jobs:
  amalgam:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        gcc amalgam-script.c -o amalgam-script
        ./amalgam-script

    - name: Configure Git
      run: |
        git config user.name 'Auto Doronin'
        git config user.email 'lyosha.doronin@gmail.com'

    - name: Check for changes
      id: git-check
      run: |
        git status
        echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changed != '0'
      run: |
        git commit -a -m "[CI] Amalgam"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}